### ISSUE TITLE
Доменное имя

### ISSUE THREAD

**Issue by NoLupiPls** [ktnk-dev/mira.ml#1]
Поставь доменное имя новое, либо архивируй проект и закрой Гитхаб страницы :)

**Comment by ktnk-dev** [comment]
Прошу прощения за столь **долгий** ответ, @NoLupiPls.
Как оказалось доменное имя истекло еще в прошлом году. Бот давно не поддерживается и не хостится после переезда на новый сервер, ввиду его нецелесообразности, и крайне посредственным функционалом, который качественно реализован в других ботах в Discord, поэтому я даже не заглядывал в репозитории связанные с ботом.

Как дань памяти моему первому большому проекту - боту, я оставлю сайт бота работающим на новом домене: http://mira.sinya.ru/
Когда-нибудь сайт точно будет готовым, а не на стадии разработки, но это совсем уже на грани фантастики
